name = "hfa-map"
type = "webpack"
account_id = "9a528f69de44167d6e10333ab59f7b23"
workers_dev = false
route = "projectendinghunger.org/*"
zone_id = "f28d8d314d8752e92d6afe3fc1cdb7cd"

[site]
bucket = "./build"
entry-point = "workers-site"
