name: CD-CD

on:
  push:
    branches: [ master ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    env:
      REACT_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.REACT_APP_GOOGLE_MAPS_API_KEY }}
      REACT_APP_ALGOLIA_APPLICATION_ID: ${{ secrets.REACT_APP_ALGOLIA_APPLICATION_ID }}
      REACT_APP_ALGOLIA_READ_ONLY_API_KEY: ${{ secrets.REACT_APP_ALGOLIA_READ_ONLY_API_KEY }}
      REACT_APP_ALGOLIA_INDEX: ${{ secrets.REACT_APP_ALGOLIA_INDEX }}
    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@v2
    - name: Setup Node Environment
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Resolve Project Dependencies Using yarn
      run: yarn && yarn build
    - name: Deploy to Cloudflare Workers with Wrangler
      uses: cloudflare/wrangler-action@1.2.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
